jenkins:
  systemMessage: "<div style='font-size:160%; background-color: powerblue;'>This Jenkins configure-test</div>"
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: github_ssh
              username: 2core3
              description: "SSH Github"
              privateKeySource:
                directEntry:
                  privateKey: ${github_ssh}
          - basicSSHUserPrivateKey:
              description: "aws_ssh"
              id: "aws_ssh"
              privateKeySource:
                directEntry:
                  privateKey: "${aws_ssh}"
              scope: GLOBAL
              username: "ubuntu"
          - string:
              scope: GLOBAL
              id: "aws_access"
              secret: "${accessKey}"
              description: "aws accessKey"
          - string:
              scope: GLOBAL
              id: "aws_secret"
              secret: "${secretKey}"
              description: "aws secretKey"
          - usernamePassword:
              description: "dockerhub"
              id: "dockerhub"
              password: "${dockerhubKey}"
              scope: GLOBAL
              username: "1core2"
          - string:
              description: "telegram_id"
              id: "telegram_id"
              scope: GLOBAL
              secret: "${telegram_id}"
          - string:
              description: "telegram_api"
              id: "telegram_api"
              scope: GLOBAL
              secret: "${telegram_api}"    
          - usernamePassword:
              scope: GLOBAL
              id: github_PAT
              password: ${github_pat}
              username: 2core3

security:
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "noHostKeyVerificationStrategy"

unclassified:
  location:
    url: ${JENKINS_URL}
  locale:
    ignoreAcceptLanguage: true
    systemLocale: "EN"
jobs:
  - file: /var/jenkins_home/casc_configs/seedjob.groovy 